### ISSUE TITLE
Volunteer View Page - Display [Due 3/6]

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG-Obsolete#345]
- **Web Path**
Home Page -> Volunteers -> Click a volunteer

- **Requirement**
Display the page as shown in wireframe
More detailed requirement will be provided when this task is assigned.

- **Wireframe**
![image](https://cloud.githubusercontent.com/assets/24813620/23350576/259ea742-fc81-11e6-8ff6-25914cd1a342.png)

- **Current Page**
![image](https://cloud.githubusercontent.com/assets/24813620/23350591/340c2a20-fc81-11e6-903c-bc9500cb4cec.png)

**Comment by politologu** [comment]
look awesome

**Comment by sabrinadowla14** [comment]
Hi Jenny,

Is this for me? Please let me know.


Thanks,
Sabrina

**Comment by Code4SocialGood** [comment]
Assigned :)

**Comment by sabrinadowla14** [comment]
Hi Jenny,

In my eclipse I am having following error.
[image: Inline image 1]

In my browser, I am not able to see the output.

[image: Inline image 2]

Need help.

Thanks,

Sabrina

**Comment by sabrinadowla14** [comment]
Hi Jenny,


I have just submited my work (Display #345)
You need to only see the user-view.component.css and
user-view.component.html
I had to work on older version, since I am not able to see the newer
version.
Somehow in newer version the node module folder is empty. I have deleted
the node module and tried npm install but still did not work.
Please let me if I need to update anything else.

Thanks,

Sabrina

**Comment by sabrinadowla14** [comment]
Hi Jenny,

Did you assign me anything for this week? Would you please let me know.

Thanks,
Sabrina

**Comment by Code4SocialGood** [comment]
Hi Sabrina,

Sorry that I haven't assigned you a task yet, we are busy working on
setting up the test server, so that you as a front end developer doesn't
have to run the back end locally :)

I will get back to you in a couple of hours with a task.

Thanks,
Jenny Wang
Code for Social Good

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-web#61
